// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_SVNEZye5APRzgvCajh1NJ8-vtaxz65s',
    appId: '1:949064716566:web:a881d17d90dfac1ee74037',
    messagingSenderId: '949064716566',
    projectId: 'wheat-rust-guard',
    authDomain: 'wheat-rust-guard.firebaseapp.com',
    storageBucket: 'wheat-rust-guard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTFFfqzcacBIQ541TROA3H1JRHWKVDTFs',
    appId: '1:949064716566:android:74fddc5b81cd4e69e74037',
    messagingSenderId: '949064716566',
    projectId: 'wheat-rust-guard',
    storageBucket: 'wheat-rust-guard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoXyGbcYEUeoj8nkKeV0zWMB0_A-rgY4',
    appId: '1:949064716566:ios:7bb5782444aa65a0e74037',
    messagingSenderId: '949064716566',
    projectId: 'wheat-rust-guard',
    storageBucket: 'wheat-rust-guard.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzoXyGbcYEUeoj8nkKeV0zWMB0_A-rgY4',
    appId: '1:949064716566:ios:7bb5782444aa65a0e74037',
    messagingSenderId: '949064716566',
    projectId: 'wheat-rust-guard',
    storageBucket: 'wheat-rust-guard.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_SVNEZye5APRzgvCajh1NJ8-vtaxz65s',
    appId: '1:949064716566:web:b1a1dc0aae3c33b0e74037',
    messagingSenderId: '949064716566',
    projectId: 'wheat-rust-guard',
    authDomain: 'wheat-rust-guard.firebaseapp.com',
    storageBucket: 'wheat-rust-guard.firebasestorage.app',
  );
}
