// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHF7kT3OwdJe6AHqyp-rRr-CGGW0wkAeM',
    appId: '1:601286020183:web:14e35039e1c1768852e712',
    messagingSenderId: '601286020183',
    projectId: 'wheat-rust-guard-89a1e',
    authDomain: 'wheat-rust-guard-89a1e.firebaseapp.com',
    storageBucket: 'wheat-rust-guard-89a1e.firebasestorage.app',
    measurementId: 'G-VR4ZKEFY5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJqaGa5Ms9GgWOQ0UHc_sQbHLoCWiGAC8',
    appId: '1:601286020183:android:e98f24f0c418bf7f52e712',
    messagingSenderId: '601286020183',
    projectId: 'wheat-rust-guard-89a1e',
    storageBucket: 'wheat-rust-guard-89a1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNJDmG0_zZrGjqD_5oR4fETFUQPVUzAfk',
    appId: '1:601286020183:ios:8c649eb1436186bf52e712',
    messagingSenderId: '601286020183',
    projectId: 'wheat-rust-guard-89a1e',
    storageBucket: 'wheat-rust-guard-89a1e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNJDmG0_zZrGjqD_5oR4fETFUQPVUzAfk',
    appId: '1:601286020183:ios:8c649eb1436186bf52e712',
    messagingSenderId: '601286020183',
    projectId: 'wheat-rust-guard-89a1e',
    storageBucket: 'wheat-rust-guard-89a1e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHF7kT3OwdJe6AHqyp-rRr-CGGW0wkAeM',
    appId: '1:601286020183:web:daa0fc9829883ac052e712',
    messagingSenderId: '601286020183',
    projectId: 'wheat-rust-guard-89a1e',
    authDomain: 'wheat-rust-guard-89a1e.firebaseapp.com',
    storageBucket: 'wheat-rust-guard-89a1e.firebasestorage.app',
    measurementId: 'G-ETYXGD03EN',
  );
}
